package dev.mcai.companion.codex;

import com.google.gson.*;
import java.util.*;
import dev.mcai.companion.agent.AgentRuntime;
import dev.mcai.companion.agent.body.HeadlessPlayerSession;
import dev.mcai.companion.agent.knowledge.*;
import dev.mcai.companion.agent.navigation.NavigationToolCoordinator;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.world.item.*;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.Vec3;
import net.minecraftforge.gametest.*;

/** Source-informed native world gate. Setup mutations are not model actions or gameplay evidence. */
@GameTestNamespace("mcai_companion") @GameTestDontPrefix
public final class ItemDropGameTests {
    private static UUID denied;
    static {net.minecraftforge.event.entity.item.ItemTossEvent.BUS.addListener(e->{return e.getPlayer().getUUID().equals(denied);});}
    @GameTest(name="item_drop_regressions",structure="forge:empty48x32x48",maxTicks=2000,padding=8)
    public static void run(GameTestHelper h){if(!Boolean.getBoolean("minepilot.dropTest")){h.fail("Explicit drop gate required");return;}new Gate(h).start();}
    private static final class Gate {
        final GameTestHelper h;final AgentRuntime r;final CodexToolService tools;final BlockPos origin;final List<ItemEntity> spawned=new ArrayList<>();
        HeadlessPlayerSession human;int phase;long since;String nav,mine;Vec3 start;BlockPos stone;ItemEntity abandoned,other,merged;JsonArray evidence=new JsonArray();
        Gate(GameTestHelper h){this.h=h;r=AgentRuntime.active(h.getLevel().getServer());tools=new CodexToolService(r);origin=h.absolutePos(new BlockPos(12,4,20));}
        JsonObject call(String name,JsonObject args,boolean success){var params=new JsonObject();params.addProperty("name",name);params.add("arguments",args);var request=new JsonObject();request.add("params",params);var reply=tools.dispatch("tools/call",request);h.assertTrue(reply.get("isError").getAsBoolean()!=success,"Unexpected "+name+": "+reply);return success?reply.getAsJsonObject("structuredContent"):reply;}
        JsonObject json(String s){return JsonParser.parseString(s).getAsJsonObject();}
        JsonObject selection(int slot,int n){var a=new JsonObject();a.addProperty("slot",slot);a.addProperty("entry_id",r.player().inventoryLedger.key(r.player().getInventory().getItem(slot)));a.addProperty("count",n);return a;}
        JsonObject args(String key,int slot,int n){var a=new JsonObject();a.addProperty("request_key",key);a.addProperty("reason","player_request");a.addProperty("player_request","Drop exactly the specified carried items for this native test");var items=new JsonArray();items.add(selection(slot,n));a.add("items",items);return a;}
        ItemEntity physical(JsonObject result,int n){h.assertTrue(result.get("phase").getAsString().equals("COMPLETED") && result.get("actualDroppedCount").getAsInt()==n,"Wrong drop outcome: "+result);var row=result.getAsJsonArray("receipts").get(0).getAsJsonObject();var e=r.player().level().getEntity(UUID.fromString(row.get("entityId").getAsString()));h.assertTrue(e instanceof ItemEntity && ((ItemEntity)e).getItem().getCount()==n,"Receipt lacks matching world entity");var drop=(ItemEntity)e;spawned.add(drop);h.assertTrue(DropProvenance.source(drop,r.player()).get("lineageCount").getAsInt()==n,"Counted origin lost");evidence.add(result);return drop;}
        void stage(int p){phase=p;since=h.getTick();}
        void start(){var p=r.player();for(int x=-5;x<=20;x++)for(int z=-5;z<=5;z++){h.getLevel().setBlock(origin.offset(x,-1,z),Blocks.STONE.defaultBlockState(),2);for(int y=0;y<4;y++)h.getLevel().setBlock(origin.offset(x,y,z),Blocks.AIR.defaultBlockState(),2);}
            p.setPos(Vec3.atBottomCenterOf(origin));p.setDeltaMovement(Vec3.ZERO);p.setOnGround(true);p.stopControlling();p.setGameMode(GameType.SURVIVAL);p.level().getChunkSource().move(p);p.getInventory().clearContent();p.inventoryLedger.tick();
            h.addCleanup(ignored->{denied=null;spawned.forEach(ItemEntity::discard);if(human!=null)human.close();r.mining().cancelForChat();r.placement().cancelForChat();r.onChat("TestHuman","停下");});
            p.getInventory().setItem(10,new ItemStack(Items.APPLE,5));p.inventoryLedger.tick();var a=args("exact-two",10,2);a.addProperty("reason","capacity");call("drop_items",a,false);h.assertTrue(p.getInventory().countItem(Items.APPLE)==5,"Protected rejection spent items");
            a.addProperty("reason","player_request");physical(call("drop_items",a,true),2);h.assertTrue(p.getInventory().countItem(Items.APPLE)==3,"Partial stack quantity wrong");var replay=call("drop_items",a,true);h.assertTrue(replay.get("replayed").getAsBoolean() && p.getInventory().countItem(Items.APPLE)==3,"Retry duplicated a toss");
            var restart=new ItemDropService(r).drop(a);h.assertTrue(restart.get("replayed").getAsBoolean(),"Receipt did not survive service reload");
            a.getAsJsonArray("items").get(0).getAsJsonObject().addProperty("count",1);call("drop_items",a,false);
            var stale=args("stale",10,1);stale.getAsJsonArray("items").get(0).getAsJsonObject().addProperty("entry_id","wrong");call("drop_items",stale,false);call("drop_items",args("absent-count",10,4),false);
            denied=p.getUUID();var cancelled=call("drop_items",args("cancelled-native",10,2),true);denied=null;h.assertTrue(cancelled.get("phase").getAsString().equals("CANCELLED") && p.getInventory().countItem(Items.APPLE)==3,"Cancelled toss lost items");evidence.add(cancelled);
            for(int slot=0;slot<36;slot++)p.getInventory().setItem(slot,new ItemStack(Items.STONE,64));p.getInventory().setItem(40,new ItemStack(Items.ENDER_PEARL,3));p.inventoryLedger.tick();physical(call("drop_items",args("full-offhand",40,2),true),2);h.assertTrue(p.getOffhandItem().getCount()==1 && p.getInventory().countItem(Items.STONE)==2304,"Full inventory/offhand mutation wrong");
            p.getInventory().clearContent();var one=new ItemStack(Items.WOODEN_PICKAXE);var two=new ItemStack(Items.WOODEN_PICKAXE);two.setDamageValue(4);p.getInventory().setItem(10,one);p.getInventory().setItem(11,two);p.inventoryLedger.tick();var ambiguous=json("{\"request_key\":\"ambiguous\",\"reason\":\"player_request\",\"player_request\":\"drop one tool\",\"items\":[{\"item\":\"minecraft:wooden_pickaxe\",\"count\":1}]}");call("drop_items",ambiguous,false);var exact=args("worn-tool",11,1);exact.getAsJsonArray("items").get(0).getAsJsonObject().addProperty("expected_damage",4);var worn=physical(call("drop_items",exact,true),1);h.assertTrue(worn.getItem().getDamageValue()==4 && p.getInventory().getItem(10).getDamageValue()==0,"Tool variants conflated");
            spawned.forEach(ItemEntity::discard);p.getInventory().clearContent();p.inventoryLedger.tick();
            r.server().getCommands().performPrefixedCommand(r.server().createCommandSourceStack(),"give MinePilot minecraft:apple 70");p.inventoryLedger.tick();
            var batch=call("drop_items",json("{\"request_key\":\"multi-stack\",\"reason\":\"player_request\",\"player_request\":\"Drop 66 apples\",\"items\":[{\"item\":\"minecraft:apple\",\"count\":66}]}"),true);int physicalCount=0;
            for(var v:batch.getAsJsonArray("receipts")){var row=v.getAsJsonObject();var e=(ItemEntity)p.level().getEntity(UUID.fromString(row.get("entityId").getAsString()));h.assertTrue(e!=null && e.isAlive(),"Batch entity absent");spawned.add(e);physicalCount+=e.getItem().getCount();var origins=DropProvenance.source(e,p);h.assertTrue(origins.get("allOriginsKnown").getAsBoolean(),"Known native give lost its origin during tool toss: "+origins);}
            h.assertTrue(physicalCount==66 && p.getInventory().countItem(Items.APPLE)==4 && batch.getAsJsonArray("receipts").size()==2,"Multi-stack quantity not conserved");evidence.add(batch);
            spawned.forEach(ItemEntity::discard);p.getInventory().clearContent();p.getInventory().setItem(0,new ItemStack(Items.WOODEN_PICKAXE));p.getInventory().setItem(10,new ItemStack(Items.APPLE,10));p.inventoryLedger.tick();start=p.position();
            var target=new JsonObject();target.addProperty("target_kind","coordinates");target.addProperty("x",start.x+8);target.addProperty("y",start.y);target.addProperty("z",start.z);target.addProperty("acceptance_radius",.7);target.addProperty("preferred_pace","walk");target.addProperty("player_intent","Walk while discarding unrelated apples");nav=call("request_navigation",target,true).get("requestId").getAsString();call("say",json("{\"message\":\"走路时也能丢东西。\",\"navigation_request_id\":\""+nav+"\"}"),true);call("plan_navigation",json("{\"request_id\":\""+nav+"\"}"),true);stage(0);h.onEachTick(()->{try{tick();}catch(RuntimeException failure){dev.mcai.companion.MinecraftAiCompanion.LOGGER.error("Drop gate assertion at phase {}: {}",phase,failure.getMessage());throw failure;}});
        }
        void tick(){var p=r.player();h.assertTrue(h.getTick()-since<500,"Drop gate timeout phase="+phase);if(human!=null)human.tick();
            if(phase==0 && r.navigation().status().phase()==NavigationToolCoordinator.Phase.PLAN_READY){var route=r.navigation().status().routeOptions().stream().filter(o->o.feasibleNow() && o.supportBlocksRequired()==0).findFirst().orElseThrow();call("choose_navigation",json("{\"request_id\":\""+nav+"\",\"option_id\":\""+route.optionId()+"\",\"pace\":\"walk\"}"),true);stage(1);}
            else if(phase==1 && p.position().distanceTo(start)>1){float yaw=p.getYRot();physical(call("drop_items",args("walking",10,3),true),3);h.assertTrue(r.navigation().status().phase()==NavigationToolCoordinator.Phase.EXECUTING && nav.equals(r.navigation().status().requestId().toString()) && p.getYRot()==yaw,"Drop interrupted/turned walking");stage(2);}
            else if(phase==2 && r.navigation().status().phase()==NavigationToolCoordinator.Phase.COMPLETED){h.assertTrue(p.position().distanceTo(start.add(8,0,0))<.8,"Walking failed physical destination");stone=p.blockPosition().north();h.getLevel().setBlock(stone,Blocks.STONE.defaultBlockState(),2);mine=call("plan_mining",TreeSurveyPosition(stone),true).get("requestId").getAsString();call("choose_mining",json("{\"request_id\":\""+mine+"\",\"option_id\":\"held-tool\"}"),true);stage(3);}
            else if(phase==3 && r.mining().status().get("breakProgress").getAsDouble()>.1){p.getInventory().setItem(12,new ItemStack(Items.WOODEN_PICKAXE));p.inventoryLedger.tick();call("drop_items",args("reserved-pick",0,1),false);physical(call("drop_items",args("spare-pick",12,1),true),1);physical(call("drop_items",args("mining",10,2),true),2);call("say",json("{\"message\":\"挖石头时也能整理背包。\"}"),true);h.assertTrue(r.mining().running(),"Drop or chat interrupted native mining");stage(4);}
            else if(phase==4 && r.mining().phase().equals("COMPLETED")){h.assertTrue(h.getLevel().getBlockState(stone).isAir() && p.getMainHandItem().getDamageValue()==1,"Native stone break/durability failed");spawned.forEach(ItemEntity::discard);abandoned=physical(call("drop_items",args("merge-avoid",10,2),true),2);var at=p.position().add(3,0,0);abandoned.setPos(at);abandoned.setDeltaMovement(Vec3.ZERO);abandoned.setNoPickUpDelay();other=new ItemEntity(h.getLevel(),at.x,at.y,at.z,new ItemStack(Items.APPLE,3));other.setNoPickUpDelay();other.setDeltaMovement(Vec3.ZERO);h.getLevel().addFreshEntity(other);spawned.add(other);stage(5);}
            else if(phase==5){merged=abandoned.isAlive() && abandoned.getItem().getCount()==5?abandoned:other.isAlive() && other.getItem().getCount()==5?other:null;if(merged==null)return;h.assertTrue(DiscardedItems.avoided(merged,p),"Native merge lost owner avoidance");p.setPos(merged.position());p.setDeltaMovement(Vec3.ZERO);p.stopControlling();stage(6);}
            else if(phase==6 && h.getTick()-since>4){h.assertTrue(merged.isAlive() && merged.getItem().getCount()==5 && p.getInventory().countItem(Items.APPLE)==3,"Owner automatically recovered its abandoned mixed stack");human=HeadlessPlayerSession.join(r.server(),h.getLevel(),"item-drop-gate","DropHuman",p.getX(),p.getY(),p.getZ());human.player().setGameMode(GameType.SURVIVAL);human.player().getInventory().clearContent();human.player().setPos(merged.position());stage(7);}
            else if(phase==7 && human.player().getInventory().countItem(Items.APPLE)==5){h.assertTrue(!merged.isAlive() && p.getInventory().countItem(Items.APPLE)==3,"Other-player pickup not physical or owner also acquired");human.close();human=null;abandoned=physical(call("drop_items",args("reclaim",10,1),true),1);abandoned.setNoPickUpDelay();abandoned.setPos(p.position());abandoned.setDeltaMovement(Vec3.ZERO);stage(8);}
            else if(phase==8 && h.getTick()-since>3){h.assertTrue(abandoned.isAlive() && p.getInventory().countItem(Items.APPLE)==2,"Reclaim fixture picked up before permission");call("reclaim_drop",json("{\"entity_id\":\""+abandoned.getUUID()+"\"}"),true);stage(9);}
            else if(phase==9 && !abandoned.isAlive()){h.assertTrue(p.getInventory().countItem(Items.APPLE)==3,"Reclaim did not physically restore one apple");for(int slot=0;slot<=40;slot++)if(p.getInventory().getItem(slot).is(Items.COBBLESTONE))p.getInventory().setItem(slot,ItemStack.EMPTY);h.getLevel().getEntitiesOfClass(ItemEntity.class,p.getBoundingBox().inflate(16),e->e.getItem().is(Items.COBBLESTONE)).forEach(ItemEntity::discard);p.getInventory().setItem(20,new ItemStack(Items.COBBLESTONE,5));p.inventoryLedger.tick();var cells=new JsonArray();for(int z=0;z<2;z++){var cell=TreeSurveyPosition(p.blockPosition().east(2).south(z));cell.addProperty("item","minecraft:cobblestone");cells.add(cell);}var placement=new JsonObject();placement.add("targets",cells);placement.addProperty("allow_movement",false);var plan=call("plan_placement",placement,true);String request=plan.get("requestId").getAsString();call("choose_placement",json("{\"request_id\":\""+request+"\",\"option_id\":\"bounded-placement\"}"),true);call("drop_items",args("reserved-building",20,4),false);physical(call("drop_items",args("building-excess",20,3),true),3);h.assertTrue(r.placement().ownsBody(),"Dropping excess cancelled placement");stone=p.blockPosition().east(2);stage(10);}
            else if(phase==10 && r.placement().status().get("phase").getAsString().equals("COMPLETED")){h.assertTrue(h.getLevel().getBlockState(stone).is(Blocks.COBBLESTONE) && h.getLevel().getBlockState(stone.south()).is(Blocks.COBBLESTONE),"Reserved building materials did not become physical blocks");dev.mcai.companion.MinecraftAiCompanion.LOGGER.info("Item drop gate passed: exact/storage/offhand/full/variants/protected/cancel/retry/multi-stack/origins/walk/mine/reservation/merge/other-player/reclaim/placement evidence={}",evidence);stage(11);h.succeed();}
        }
        JsonObject TreeSurveyPosition(BlockPos p){return dev.mcai.companion.agent.mining.TreeSurvey.position(p);}
    }
}
