package dev.mcai.companion.progression;

/**
 * Compact strategic objective selected from the next unverified route
 * milestone. It is guidance, not evidence or a direct world action.
 */
public enum SurvivalRouteObjective {
    GATHER_VISIBLE_WOOD,
    PREPARE_BASIC_CRAFTING,
    SECURE_FOOD_RESERVE,
    CRAFT_AND_MINE_STONE,
    DISTRIBUTE_LOG_STORAGE,
    RETRIEVE_CONTAINER_WOOD_AND_PLACE_DOOR,
    ACQUIRE_IRON_TOOLKIT,
    ESTABLISH_FOUNDATION_WORKSTATIONS,
    STORE_SURPLUS_SUPPLIES,
    BUILD_DYNAMIC_SHELTER,
    SURVIVE_OR_SLEEP_THROUGH_NIGHT,
    BUILD_AND_VERIFY_NETHER_ROUTE,
    FIND_AND_ACQUIRE_BLAZE_MATERIAL,
    ACQUIRE_ENDER_PEARLS,
    CRAFT_EYES_OF_ENDER,
    TRACE_STRONGHOLD_BEARING,
    TRIANGULATE_STRONGHOLD_SEARCH_AREA,
    PREPARE_END_LOADOUT,
    ACTIVATE_AND_ENTER_END_PORTAL,
    REACH_END_ISLAND,
    DEFEAT_ENDER_DRAGON,
    ENTER_RETURN_PORTAL
}
