package dev.mcai.companion.model;

public enum ModelFailureKind {
    INVALID_CONFIGURATION,
    AUTHENTICATION,
    PERMISSION,
    BILLING,
    MODEL_NOT_FOUND,
    ENDPOINT_UNSUPPORTED,
    CAPABILITY_UNSUPPORTED,
    RATE_LIMITED,
    SERVER_TRANSIENT,
    NETWORK_TRANSIENT,
    TIMEOUT,
    CONTENT_FILTERED,
    CONTEXT_LIMIT,
    INVALID_REQUEST,
    MALFORMED_RESPONSE,
    CANCELLED,
    STALE_RESPONSE,
    BUSY,
    INTERNAL
}
